export interface TotalReport {
    CONTROLLED_TRAFFIC_SYSTEM: number
	CORRECTIVE_QUALITY: number
	CROP_ROTATION: number
	IRRIGATION_USE_EFFICIENCY: number
	PHYTOSANITARY: number
	SOIL_RECHARGE_AND_MOISTURE: number
	SOIL_TEMPERATURE: number
	SUSTAINABLE: number
	WATER_RUNOFF_CONTAINMENT: number
}